"""Add parent_id to Ticket

Revision ID: 6523e01bb988
Revises: 9c61fe152d41
Create Date: 2026-03-23 16:34:40.442391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6523e01bb988"
down_revision: Union[str, Sequence[str], None] = "9c61fe152d41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_tickets_parent_id_tickets", "tickets", ["parent_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_constraint("fk_tickets_parent_id_tickets", type_="foreignkey")
        batch_op.drop_column("parent_id")

    # ### end Alembic commands ###
