"""Add due_date to Ticket

Revision ID: 9c61fe152d41
Revises: cb8b7155ded5
Create Date: 2026-03-23 16:20:37.400172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c61fe152d41"
down_revision: Union[str, Sequence[str], None] = "cb8b7155ded5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("due_date", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_column("due_date")

    # ### end Alembic commands ###
