"""Initial schema

Revision ID: b00dc4b8ba72
Revises:
Create Date: 2026-03-23 14:02:50.380246

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b00dc4b8ba72"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("priority", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("resolution_reason", sa.Text(), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("resolution_md", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index("comments_ticket_id_idx", ["ticket_id"], unique=False)

    op.create_table(
        "links",
        sa.Column("ticket_a_id", sa.Integer(), nullable=False),
        sa.Column("ticket_b_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.CheckConstraint("ticket_a_id < ticket_b_id"),
        sa.ForeignKeyConstraint(["ticket_a_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ticket_b_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ticket_a_id", "ticket_b_id"),
    )
    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.create_index("links_ticket_b_idx", ["ticket_b_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.drop_index("links_ticket_b_idx")

    op.drop_table("links")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index("comments_ticket_id_idx")

    op.drop_table("comments")
    op.drop_table("tickets")
    op.drop_table("settings")
    # ### end Alembic commands ###
