"""Add labels to Ticket

Revision ID: cb8b7155ded5
Revises: b00dc4b8ba72
Create Date: 2026-03-23 14:30:40.746508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb8b7155ded5"
down_revision: Union[str, Sequence[str], None] = "b00dc4b8ba72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("labels", sa.String(), nullable=False, server_default=""))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_column("labels")

    # ### end Alembic commands ###
